# Operating system (build VM template)
os: Visual Studio 2015

platform: x64

clone_folder: c:\gopath\src\github.com\minio\minio

# environment variables
environment:
  GOPATH: c:\gopath
  GO_EXTLINK_ENABLED: 0
  GO15VENDOREXPERIMENT: 1

# scripts that run after cloning repository
install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rd C:\Go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.windows-amd64.zip
  - 7z x go1.6.windows-amd64.zip -oC:\ >nul
  - go version
  - go env
  - cd %GOPATH%\src\github.com\minio\minio

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go test .
  - go test -race .
  - go test github.com/minio/minio/pkg...
  - go test -race github.com/minio/minio/pkg...
  - go run buildscripts/gen-ldflags.go > temp.txt
  - set /p BUILD_LDFLAGS=<temp.txt
  - go build -ldflags="%BUILD_LDFLAGS%" -o %GOPATH%\bin\minio.exe

# to disable automatic tests
test: off

# to disable deployment
deploy: off
